/**
 * Dummy/Mock Data for Feature Screens
 * Used for development, testing, and fallback when API is unavailable
 */

export const MOCK_ROUTES = [
  {
    id: '1',
    name: 'Mountain Peak Adventure',
    distance: '12 km',
    duration: '4h 30m',
    difficulty: 'hard' as const,
    status: 'completed' as const,
    startedAt: '7 days ago',
  },
  {
    id: '2',
    name: 'Forest Trail Walk',
    distance: '8.5 km',
    duration: '2h 45m',
    difficulty: 'easy' as const,
    status: 'completed' as const,
    startedAt: '14 days ago',
  },
  {
    id: '3',
    name: 'Coastal Beach Route',
    distance: '15 km',
    duration: '5h 20m',
    difficulty: 'medium' as const,
    status: 'in-progress' as const,
    startedAt: '2 days ago',
  },
  {
    id: '4',
    name: 'Urban City Explorer',
    distance: '10 km',
    duration: '3h',
    difficulty: 'easy' as const,
    status: 'in-progress' as const,
    startedAt: '1 day ago',
  },
  {
    id: '5',
    name: 'Highland Summit Challenge',
    distance: '20 km',
    duration: '7h 15m',
    difficulty: 'hard' as const,
    status: 'planned' as const,
    startedAt: null,
  },
  {
    id: '6',
    name: 'River Valley Discovery',
    distance: '9 km',
    duration: '3h 30m',
    difficulty: 'medium' as const,
    status: 'planned' as const,
    startedAt: null,
  },
];

export const MOCK_CHALLENGES = [
  {
    id: '1',
    name: 'Meditation Mastery',
    description: 'Complete 10 minutes of daily meditation',
    category: 'wellness',
    progress: 18,
    totalSteps: 30,
    daysLeft: 12,
    difficulty: 'easy' as const,
    reward: 150,
    startedAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 12 * 24 * 60 * 60 * 1000,
  },
  {
    id: '2',
    name: 'Creative Writing Sprint',
    description: 'Write 500 words daily for 14 days',
    category: 'creativity',
    progress: 8,
    totalSteps: 14,
    daysLeft: 6,
    difficulty: 'medium' as const,
    reward: 300,
    startedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 6 * 24 * 60 * 60 * 1000,
  },
  {
    id: '3',
    name: 'Fitness Quest',
    description: 'Complete 30 minute workouts',
    category: 'fitness',
    progress: 5,
    totalSteps: 21,
    daysLeft: 16,
    difficulty: 'hard' as const,
    reward: 500,
    startedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 16 * 24 * 60 * 60 * 1000,
  },
  {
    id: '4',
    name: 'Learning Languages',
    description: 'Learn 10 new words in a new language',
    category: 'learning',
    progress: 10,
    totalSteps: 10,
    daysLeft: 0,
    difficulty: 'easy' as const,
    reward: 200,
    startedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    endsAt: Date.now(),
  },
  {
    id: '5',
    name: 'Artistic Expression',
    description: 'Create daily art pieces',
    category: 'creativity',
    progress: 2,
    totalSteps: 7,
    daysLeft: 5,
    difficulty: 'easy' as const,
    reward: 250,
    startedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 5 * 24 * 60 * 60 * 1000,
  },
];

export const MOCK_CONNECTIONS = [
  {
    id: '1',
    name: 'Alex Chen',
    status: 'close' as const,
    sharedMoments: 24,
    lastInteraction: '2 hours ago',
    vibe: '🎨 Artist',
  },
  {
    id: '2',
    name: 'Jordan Smith',
    status: 'friend' as const,
    sharedMoments: 15,
    lastInteraction: '1 day ago',
    vibe: '🏃 Adventurer',
  },
  {
    id: '3',
    name: 'Casey Kim',
    status: 'friend' as const,
    sharedMoments: 12,
    lastInteraction: '3 days ago',
    vibe: '📚 Thinker',
  },
  {
    id: '4',
    name: 'Morgan Lee',
    status: 'acquaintance' as const,
    sharedMoments: 5,
    lastInteraction: '1 week ago',
    vibe: '🎵 Musician',
  },
  {
    id: '5',
    name: 'Taylor West',
    status: 'acquaintance' as const,
    sharedMoments: 3,
    lastInteraction: '2 weeks ago',
    vibe: '✨ Creator',
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: 'Alex Chen', score: 8450, trend: 'up' as const, badges: '🏆🎨✨' },
  { rank: 2, name: 'Jordan Smith', score: 7820, trend: 'stable' as const, badges: '🥈🏃' },
  { rank: 3, name: 'You', score: 6540, trend: 'up' as const, badges: '🥉🚀' },
  { rank: 4, name: 'Sam Taylor', score: 5120, trend: 'down' as const, badges: '🎨💪' },
  { rank: 5, name: 'Morgan Lee', score: 4890, trend: 'up' as const, badges: '🎵✨' },
  { rank: 6, name: 'Casey Kim', score: 3450, trend: 'stable' as const, badges: '📚🧠' },
  { rank: 7, name: 'Riley Johnson', score: 3120, trend: 'down' as const, badges: '🌟💙' },
  { rank: 8, name: 'Phoenix Day', score: 2890, trend: 'up' as const, badges: '🔥🎯' },
];

export const MOCK_SHOP_ITEMS = [
  {
    id: '1',
    name: 'Meditation Boost',
    description: '2x meditation rewards',
    category: 'power-up',
    price: 500,
    icon: '🧘',
    owned: false,
  },
  {
    id: '2',
    name: 'Lucky Charm',
    description: 'Increase success rate by 15%',
    category: 'power-up',
    price: 750,
    icon: '🍀',
    owned: false,
  },
  {
    id: '3',
    name: 'Golden Badge',
    description: 'Rare achievement badge',
    category: 'collectible',
    price: 1000,
    icon: '🏅',
    owned: true,
  },
  {
    id: '4',
    name: 'Experience Multiplier',
    description: '3x XP for next 7 days',
    category: 'power-up',
    price: 1200,
    icon: '⚡',
    owned: false,
  },
  {
    id: '5',
    name: 'Wisdom Scroll',
    description: 'Unlock special insights',
    category: 'collectible',
    price: 600,
    icon: '📜',
    owned: false,
  },
  {
    id: '6',
    name: 'Spirit Stone',
    description: 'Rare collectible item',
    category: 'collectible',
    price: 2000,
    icon: '💎',
    owned: false,
  },
];

export const MOCK_USER_RANK = {
  rank: 3,
  name: 'You',
  score: 6540,
  totalUsers: 2450,
  percentile: 98.5,
  badges: ['🥉', '🚀', '💙'],
  achievements: [
    { id: '1', name: 'First Steps', description: 'Complete your first challenge' },
    { id: '2', name: 'Rising Star', description: 'Reach top 100 in leaderboard' },
    { id: '3', name: 'Marathon Runner', description: 'Complete 10 routes' },
  ],
};

export const MOCK_WALLET = {
  balance: 2450,
  totalEarned: 8750,
  totalSpent: 6300,
  currency: '💜 Vibe Points',
};

export const MOCK_CANVAS_ENTRIES = [
  {
    id: '1',
    title: 'Beautiful Sunset',
    content: 'Watched the most incredible sunset today. The sky was painted in shades of orange and purple.',
    emoji: '🌅',
    mood: 'peaceful',
    createdAt: '1 day ago',
    likes: 12,
  },
  {
    id: '2',
    title: 'Adventure Day',
    content: 'Hiked up the mountain and discovered a hidden waterfall. Nature is amazing!',
    emoji: '⛰️',
    mood: 'excited',
    createdAt: '3 days ago',
    likes: 28,
  },
  {
    id: '3',
    title: 'Reflective Moment',
    content: 'Taking time to reflect on my goals and dreams. Ready for new beginnings.',
    emoji: '🌙',
    mood: 'inspired',
    createdAt: '5 days ago',
    likes: 19,
  },
];
