/**
 * Dummy/Mock Data for Feature Screens
 * Used for development, testing, and fallback when API is unavailable
 */

export const MOCK_ROUTES = [
  {
    id: '1',
    name: 'Mountain Peak Adventure',
    distance: 12,
    duration: 270,
    difficulty: 'hard' as const,
    status: 'completed' as const,
    startedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: '2',
    name: 'Forest Trail Walk',
    distance: 8.5,
    duration: 165,
    difficulty: 'easy' as const,
    status: 'completed' as const,
    startedAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
  },
  {
    id: '3',
    name: 'Coastal Beach Route',
    distance: 15,
    duration: 320,
    difficulty: 'medium' as const,
    status: 'in-progress' as const,
    startedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: '4',
    name: 'Urban City Explorer',
    distance: 10,
    duration: 180,
    difficulty: 'easy' as const,
    status: 'in-progress' as const,
    startedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: '5',
    name: 'Highland Summit Challenge',
    distance: 20,
    duration: 435,
    difficulty: 'hard' as const,
    status: 'planned' as const,
  },
  {
    id: '6',
    name: 'River Valley Discovery',
    distance: 9,
    duration: 210,
    difficulty: 'medium' as const,
    status: 'planned' as const,
  },
];

export const MOCK_CHALLENGES = [
  {
    id: '1',
    name: 'Meditation Mastery',
    description: 'Complete 10 minutes of daily meditation',
    category: 'wellness',
    progress: 18,
    totalSteps: 30,
    daysLeft: 12,
    difficulty: 'easy' as const,
    reward: 150,
    startedAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 12 * 24 * 60 * 60 * 1000,
  },
  {
    id: '2',
    name: 'Creative Writing Sprint',
    description: 'Write 500 words daily for 14 days',
    category: 'creativity',
    progress: 8,
    totalSteps: 14,
    daysLeft: 6,
    difficulty: 'medium' as const,
    reward: 300,
    startedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 6 * 24 * 60 * 60 * 1000,
  },
  {
    id: '3',
    name: 'Fitness Quest',
    description: 'Complete 30 minute workouts',
    category: 'fitness',
    progress: 5,
    totalSteps: 21,
    daysLeft: 16,
    difficulty: 'hard' as const,
    reward: 500,
    startedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 16 * 24 * 60 * 60 * 1000,
  },
  {
    id: '4',
    name: 'Learning Languages',
    description: 'Learn 10 new words in a new language',
    category: 'learning',
    progress: 10,
    totalSteps: 10,
    daysLeft: 0,
    difficulty: 'easy' as const,
    reward: 200,
    startedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    endsAt: Date.now(),
  },
  {
    id: '5',
    name: 'Artistic Expression',
    description: 'Create daily art pieces',
    category: 'creativity',
    progress: 2,
    totalSteps: 7,
    daysLeft: 5,
    difficulty: 'easy' as const,
    reward: 250,
    startedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    endsAt: Date.now() + 5 * 24 * 60 * 60 * 1000,
  },
];

export const MOCK_CONNECTIONS = [
  {
    id: '1',
    name: 'Alex Chen',
    status: 'close' as const,
    sharedMoments: 24,
    lastInteraction: Date.now() - 2 * 60 * 60 * 1000,
    vibe: '🎨 Artist',
  },
  {
    id: '2',
    name: 'Jordan Smith',
    status: 'friend' as const,
    sharedMoments: 15,
    lastInteraction: Date.now() - 1 * 24 * 60 * 60 * 1000,
    vibe: '🏃 Adventurer',
  },
  {
    id: '3',
    name: 'Casey Kim',
    status: 'friend' as const,
    sharedMoments: 12,
    lastInteraction: Date.now() - 3 * 24 * 60 * 60 * 1000,
    vibe: '📚 Thinker',
  },
  {
    id: '4',
    name: 'Morgan Lee',
    status: 'acquaintance' as const,
    sharedMoments: 5,
    lastInteraction: Date.now() - 7 * 24 * 60 * 60 * 1000,
    vibe: '🎵 Musician',
  },
  {
    id: '5',
    name: 'Taylor West',
    status: 'acquaintance' as const,
    sharedMoments: 3,
    lastInteraction: Date.now() - 14 * 24 * 60 * 60 * 1000,
    vibe: '✨ Creator',
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, userId: 'user_1', name: 'Alex Chen', score: 8450, trend: 'up' as const, badges: ['🏆', '🎨', '✨'] },
  { rank: 2, userId: 'user_2', name: 'Jordan Smith', score: 7820, trend: 'stable' as const, badges: ['🥈', '🏃'] },
  { rank: 3, userId: 'user_3', name: 'You', score: 6540, trend: 'up' as const, badges: ['🥉', '🚀'] },
  { rank: 4, userId: 'user_4', name: 'Sam Taylor', score: 5120, trend: 'down' as const, badges: ['🎨', '💪'] },
  { rank: 5, userId: 'user_5', name: 'Morgan Lee', score: 4890, trend: 'up' as const, badges: ['🎵', '✨'] },
  { rank: 6, userId: 'user_6', name: 'Casey Kim', score: 3450, trend: 'stable' as const, badges: ['📚', '🧠'] },
  { rank: 7, userId: 'user_7', name: 'Riley Johnson', score: 3120, trend: 'down' as const, badges: ['🌟', '💙'] },
  { rank: 8, userId: 'user_8', name: 'Phoenix Day', score: 2890, trend: 'up' as const, badges: ['🔥', '🎯'] },
];

export const MOCK_SHOP_ITEMS = [
  {
    id: '1',
    name: 'Meditation Boost',
    description: '2x meditation rewards',
    category: 'power-up',
    price: 500,
    icon: '🧘',
    purchased: false,
  },
  {
    id: '2',
    name: 'Lucky Charm',
    description: 'Increase success rate by 15%',
    category: 'power-up',
    price: 750,
    icon: '🍀',
    purchased: false,
  },
  {
    id: '3',
    name: 'Golden Badge',
    description: 'Rare achievement badge',
    category: 'collectible',
    price: 1000,
    icon: '🏅',
    purchased: true,
  },
  {
    id: '4',
    name: 'Experience Multiplier',
    description: '3x XP for next 7 days',
    category: 'power-up',
    price: 1200,
    icon: '⚡',
    purchased: false,
  },
  {
    id: '5',
    name: 'Wisdom Scroll',
    description: 'Unlock special insights',
    category: 'collectible',
    price: 600,
    icon: '📜',
    purchased: false,
  },
  {
    id: '6',
    name: 'Spirit Stone',
    description: 'Rare collectible item',
    category: 'collectible',
    price: 2000,
    icon: '💎',
    purchased: false,
  },
];

export const MOCK_USER_RANK = {
  rank: 3,
  userId: 'user_current',
  name: 'You',
  score: 6540,
  trend: 'up' as const,
  badges: ['🥉', '🚀', '💙'],
};

export const MOCK_WALLET = {
  balance: 2450,
  totalEarned: 8750,
  totalSpent: 6300,
  currency: '💜 Vibe Points',
};

export const MOCK_CANVAS_ENTRIES = [
  {
    id: '1',
    title: 'Beautiful Sunset',
    content: 'Watched the most incredible sunset today. The sky was painted in shades of orange and purple.',
    emoji: '🌅',
    mood: 'peaceful',
    createdAt: '1 day ago',
    likes: 12,
  },
  {
    id: '2',
    title: 'Adventure Day',
    content: 'Hiked up the mountain and discovered a hidden waterfall. Nature is amazing!',
    emoji: '⛰️',
    mood: 'excited',
    createdAt: '3 days ago',
    likes: 28,
  },
  {
    id: '3',
    title: 'Reflective Moment',
    content: 'Taking time to reflect on my goals and dreams. Ready for new beginnings.',
    emoji: '🌙',
    mood: 'inspired',
    createdAt: '5 days ago',
    likes: 19,
  },
];

export const MOCK_FEED_POSTS = [
  {
    id: '1',
    author: 'Alex Journey',
    content: 'Just completed an amazing hiking trail! The views were absolutely breathtaking. Nature never ceases to amaze me 🏔️',
    timestamp: '2 hours ago',
    mood: 'joy',
    reactions: 142,
    comments: 23,
  },
  {
    id: '2',
    author: 'Sarah Mindful',
    content: 'Finished my morning meditation session. Feeling calm and centered for the day ahead. 🧘',
    timestamp: '5 hours ago',
    mood: 'calm',
    reactions: 87,
    comments: 12,
  },
  {
    id: '3',
    author: 'Jordan Creative',
    content: 'Started working on a new creative project! Super excited to see where this journey takes me 🎨',
    timestamp: '1 day ago',
    mood: 'joy',
    reactions: 156,
    comments: 34,
  },
  {
    id: '4',
    author: 'Casey Reflect',
    content: 'Taking a moment to appreciate the little things in life. Gratitude is key ✨',
    timestamp: '1 day ago',
    mood: 'reflect',
    reactions: 201,
    comments: 45,
  },
  {
    id: '5',
    author: 'Morgan Active',
    content: 'Crushed my workout goals today! 💪 Who else is on their fitness journey?',
    timestamp: '2 days ago',
    mood: 'joy',
    reactions: 234,
    comments: 56,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    type: 'like',
    title: 'Alex Journey liked your post',
    message: 'They loved your hiking trail story',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    avatar: 'AJ',
    read: false,
    icon: '💜',
  },
  {
    id: '2',
    type: 'comment',
    title: 'Sarah Mindful commented on your post',
    message: '"Great insights! Really resonates with me"',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    avatar: 'SM',
    read: false,
    icon: '💬',
  },
  {
    id: '3',
    type: 'follow',
    title: 'Jordan Creative started following you',
    message: 'Check out their amazing creative projects',
    timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
    avatar: 'JC',
    read: false,
    icon: '👤',
  },
  {
    id: '4',
    type: 'milestone',
    title: 'You reached 100 followers!',
    message: 'Congratulations on this amazing milestone',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    avatar: '',
    read: true,
    icon: '🎉',
  },
  {
    id: '5',
    type: 'achievement',
    title: 'New badge unlocked: Rising Star',
    message: 'You completed 5 challenges in one week',
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    avatar: '',
    read: true,
    icon: '⭐',
  },
  {
    id: '6',
    type: 'message',
    title: 'Casey Reflect sent you a message',
    message: '"Hey! How did your meditation session go?"',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    avatar: 'CR',
    read: true,
    icon: '💬',
  },
  {
    id: '7',
    type: 'update',
    title: 'Essenz challenge update',
    message: 'New challenge: 7-day mindfulness journey',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
    avatar: '',
    read: true,
    icon: '📢',
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: '1',
    participantId: 'user_1',
    participantName: 'Clifford Bryant',
    lastMessage: 'That sounds amazing! Let\'s definitely catch up soon.',
    lastMessageTime: Date.now() - 2 * 60000,
    unreadCount: 1,
    messages: [],
  },
  {
    id: '2',
    participantId: 'user_2',
    participantName: 'Sarah Chen',
    lastMessage: 'Did you see the new project proposal? It looks great!',
    lastMessageTime: Date.now() - (8 * 60000 + 21000),
    unreadCount: 2,
    messages: [],
  },
  {
    id: '3',
    participantId: 'user_3',
    participantName: 'Marcus Johnson',
    lastMessage: 'Thanks for the help yesterday, really appreciated it!',
    lastMessageTime: Date.now() - (8 * 60000 + 46000),
    unreadCount: 0,
    messages: [],
  },
  {
    id: '4',
    participantId: 'user_4',
    participantName: 'Emily Rodriguez',
    lastMessage: 'Looking forward to the event tomorrow! See you there 🎉',
    lastMessageTime: Date.now() - 1 * 3600000,
    unreadCount: 0,
    messages: [],
  },
  {
    id: '5',
    participantId: 'user_5',
    participantName: 'Alex Kim',
    lastMessage: 'Just finished the chapter, it was incredible!',
    lastMessageTime: Date.now() - 5 * 3600000,
    unreadCount: 0,
    messages: [],
  },
  {
    id: '6',
    participantId: 'user_6',
    participantName: 'Jordan Taylor',
    lastMessage: 'Let me know when you\'re free for coffee ☕',
    lastMessageTime: Date.now() - 1 * 86400000,
    unreadCount: 0,
    messages: [],
  },
];

export const MOCK_CONVERSATION_MESSAGES = {
  '1': [
    {
      id: '1',
      conversationId: '1',
      senderId: 'user_1',
      senderName: 'Clifford Bryant',
      content: 'Hey! How have you been?',
      timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
      read: true,
    },
    {
      id: '2',
      conversationId: '1',
      senderId: 'me',
      senderName: 'You',
      content: 'Great! Been busy with projects.',
      timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
      read: true,
    },
    {
      id: '3',
      conversationId: '1',
      senderId: 'user_1',
      senderName: 'Clifford Bryant',
      content: 'That sounds amazing! Let\'s definitely catch up soon.',
      timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
      read: true,
    },
  ],
  '2': [
    {
      id: '1',
      conversationId: '2',
      senderId: 'user_2',
      senderName: 'Sarah Chen',
      content: 'Did you see the new project proposal? It looks great!',
      timestamp: new Date(Date.now() - 8 * 60000 - 21000).toISOString(),
      read: false,
    },
  ],
};

// All users in the app for search
export const MOCK_ALL_USERS = [
  {
    id: 'user_1',
    name: 'Clifford Bryant',
    isFriend: true,
    status: 'online' as const,
  },
  {
    id: 'user_2',
    name: 'Sarah Chen',
    isFriend: true,
    status: 'online' as const,
  },
  {
    id: 'user_3',
    name: 'Marcus Johnson',
    isFriend: true,
    status: 'offline' as const,
  },
  {
    id: 'user_4',
    name: 'Emily Rodriguez',
    isFriend: true,
    status: 'online' as const,
  },
  {
    id: 'user_5',
    name: 'Alex Kim',
    isFriend: true,
    status: 'offline' as const,
  },
  {
    id: 'user_6',
    name: 'Jordan Taylor',
    isFriend: true,
    status: 'online' as const,
  },
  {
    id: 'user_7',
    name: 'David Wilson',
    isFriend: false,
    status: 'online' as const,
  },
  {
    id: 'user_8',
    name: 'Sophie Turner',
    isFriend: false,
    status: 'online' as const,
  },
  {
    id: 'user_9',
    name: 'Chris Anderson',
    isFriend: false,
    status: 'offline' as const,
  },
  {
    id: 'user_10',
    name: 'Lisa Brown',
    isFriend: false,
    status: 'online' as const,
  },
  {
    id: 'user_11',
    name: 'James Martinez',
    isFriend: false,
    status: 'offline' as const,
  },
  {
    id: 'user_12',
    name: 'Emma Davis',
    isFriend: false,
    status: 'online' as const,
  },
];
