
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('Starting RLS Security Fixes...');

    try {
        // --- 1. Enable RLS on tables with existing but disabled policies ---
        const tablesToEnableRLS = [
            'DeletedMessage',
            'Message',
            'MessageTag',
            'Trigger',
            'TriggerCollection',
        ];

        for (const table of tablesToEnableRLS) {
            try {
                await prisma.$executeRawUnsafe(`ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`);
                console.log(`✅ Enabled RLS for table: ${table}`);
            } catch (e) {
                console.error(`❌ Failed to enable RLS for ${table}:`, e);
            }
        }

        // --- 2. Secure Public Tables (Invite, VerificationToken) ---
        // Invite
        try {
            await prisma.$executeRawUnsafe(`ALTER TABLE "Invite" ENABLE ROW LEVEL SECURITY;`);
            // Drop existing if any to avoid errors
            await prisma.$executeRawUnsafe(`DROP POLICY IF EXISTS "Enable insert for inviter" ON "Invite";`);
            await prisma.$executeRawUnsafe(`DROP POLICY IF EXISTS "Enable read for inviter" ON "Invite";`);

            await prisma.$executeRawUnsafe(`
            CREATE POLICY "Enable insert for inviter" ON "Invite" 
            FOR INSERT WITH CHECK ((auth.uid())::text = "inviterId");
        `);
            await prisma.$executeRawUnsafe(`
            CREATE POLICY "Enable read for inviter" ON "Invite" 
            FOR SELECT USING ((auth.uid())::text = "inviterId");
        `);
            console.log(`✅ Secured table: Invite`);
        } catch (e) {
            console.error(`❌ Failed to secure Invite:`, e);
        }

        // VerificationToken
        try {
            await prisma.$executeRawUnsafe(`ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;`);
            // No policies = no access by default for anon/authenticated (system only)
            console.log(`✅ Secured table: VerificationToken (RLS enabled, no public access)`);
        } catch (e) {
            console.error(`❌ Failed to secure VerificationToken:`, e);
        }

        // --- 3. Fix Permissive Policies (USING true) ---
        // Strategy: Drop permissive policies, add strict write policies, keep public read where needed.

        // Helper to replace policies
        const fixPolicy = async (table: string, ownerField: string, publicRead: boolean = true) => {
            try {
                // Drop common permissive policy names if they exist (hard to know exact names, so we try a few or just add new strict ones)
                // Best attempt: We'll drop specific known weak policies if we knew names. 
                // Since we don't know exact names of existing policies, we will just CREATE specific strict ones.
                // Users noted "rls_policy_always_true". 

                // However, to be safe and effective, we should really ensure we restrict writes.
                // If a "USING (true)" policy exists for ALL operations, adding a strict one won't restrict it (policies are OR'd).
                // We MUST try to drop the "enable all" policies. 
                // Common names generated by Supabase UI: "Enable read access for all users", "Enable insert for users based on user_id", etc.

                // FOR NOW: We will assume we need to generally lock down WRITEs.
                // We'll execute a block to drop policies that look like "allow all".

                // A radical but safe approach for these specific tables:
                // Get current policies -> Drop them -> Re-create correct ones.

                const policies = await prisma.$queryRaw`
                SELECT policyname FROM pg_policies WHERE tablename = ${table};
             ` as { policyname: string }[];

                console.log(`ℹ️ Found ${policies.length} policies for ${table}: ${policies.map(p => p.policyname).join(', ')}`);

                for (const p of policies) {
                    if (p.policyname.toLowerCase().includes('all') || p.policyname.toLowerCase().includes('public') || p.policyname.toLowerCase().includes('enable')) {
                        // We'll operate carefully. 
                        // Actually, disabling the bad ones is key.
                        await prisma.$executeRawUnsafe(`DROP POLICY IF EXISTS "${p.policyname}" ON "${table}";`);
                        console.log(`   Dropped potential permissive policy: ${p.policyname}`);
                    }
                }

                // 1. SELECT (Read)
                if (publicRead) {
                    await prisma.$executeRawUnsafe(`
                    CREATE POLICY "Enable public read" ON "${table}" 
                    FOR SELECT USING (true);
                 `);
                } else {
                    await prisma.$executeRawUnsafe(`
                    CREATE POLICY "Enable read for owner" ON "${table}" 
                    FOR SELECT USING ((auth.uid())::text = "${ownerField}");
                 `);
                }

                // 2. INSERT (Create)
                await prisma.$executeRawUnsafe(`
                CREATE POLICY "Enable insert for owner" ON "${table}" 
                FOR INSERT WITH CHECK ((auth.uid())::text = "${ownerField}");
             `);

                // 3. UPDATE
                await prisma.$executeRawUnsafe(`
                CREATE POLICY "Enable update for owner" ON "${table}" 
                FOR UPDATE USING ((auth.uid())::text = "${ownerField}");
             `);

                // 4. DELETE
                await prisma.$executeRawUnsafe(`
                CREATE POLICY "Enable delete for owner" ON "${table}" 
                FOR DELETE USING ((auth.uid())::text = "${ownerField}");
             `);

                console.log(`✅ Fixed policies for: ${table}`);

            } catch (e) {
                console.error(`❌ Failed to fix policies for ${table}:`, e);
            }
        };

        // Fix Post
        await fixPolicy('Post', 'userId', true); // Public read is essential for app to work for now

        // Fix Media
        await fixPolicy('Media', 'userId', true);

        // Fix others linked to Post (Schema shows they have postId, not userId directly? Wait, let's check schema again)
        // Aud, Chan, Chapter, Fill, Lill, PullUpDown have `postId`.
        // We need to check if they have `userId` column?
        // Looking at schema in memory...
        // `Chapter`: has `postId`. schema doesn't show `userId`.
        // `Aud`: has `postId`.
        // `Lill`: has `postId`.
        // `Fill`: has `postId`.
        // `Chan`: has `postId`.

        // For these, we need a policy checking the parent Post's ownership for Writes.
        // For Reads, they should be public if Post is public.

        const childTables = ['Chapter', 'Aud', 'Chan', 'Fill', 'Lill'];
        for (const table of childTables) {
            try {
                // Drop existing
                const policies = await prisma.$queryRaw`SELECT policyname FROM pg_policies WHERE tablename = ${table};` as { policyname: string }[];
                for (const p of policies) await prisma.$executeRawUnsafe(`DROP POLICY IF EXISTS "${p.policyname}" ON "${table}";`);

                // Read
                await prisma.$executeRawUnsafe(`CREATE POLICY "Enable public read" ON "${table}" FOR SELECT USING (true);`);

                // Write (Insert/Update/Delete) - check parent Post ownership
                // NOTE: Postgres RLS for INSERT check references NEW row. 
                // Using exists on "Post"
                const policyCheck = `EXISTS (SELECT 1 FROM "Post" p WHERE p.id = "postId" AND p."userId" = (auth.uid())::text)`;

                await prisma.$executeRawUnsafe(`CREATE POLICY "Enable insert for post owner" ON "${table}" FOR INSERT WITH CHECK (${policyCheck});`);
                await prisma.$executeRawUnsafe(`CREATE POLICY "Enable update for post owner" ON "${table}" FOR UPDATE USING (${policyCheck});`);
                await prisma.$executeRawUnsafe(`CREATE POLICY "Enable delete for post owner" ON "${table}" FOR DELETE USING (${policyCheck});`);

                console.log(`✅ Fixed policies for child table: ${table}`);
            } catch (e) {
                console.error(`❌ Failed to fix policies for child ${table}:`, e);
            }
        }

    } catch (error) {
        console.error('Fatal error in RLS script:', error);
    } finally {
        await prisma.$disconnect();
    }
}

main();
